version: "3"
services:
  getepluspi:
    image: getepluspi_img
    ports:
      - "8083:8083"
    networks:
      - epluspi_net
    depends_on:
      - getpi
      - gete

  getpi:
   image: getpi_img
   ports:
     - "8081:8081"
   networks:
     - epluspi_net


  gete:
    image: gete_img
    ports:
      - "8082:8082"
    networks:
      - epluspi_net

networks:
  epluspi_net:
